#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

echo ""
echo -e "  ${CYAN}${BOLD}MJ Dev Environment${NC}  ${DIM}commands${NC}"
echo -e "  ${DIM}──────────────────────────────────────────────${NC}"
echo ""
echo -e "  ${CYAN}${BOLD}mj-start${NC}  ${DIM}[api|explorer]${NC}"
echo -e "  Start API, Explorer, or both. Ctrl-C stops all."
echo ""
echo -e "  ${CYAN}${BOLD}mj-refresh${NC}  ${DIM}[branch] [--fresh] [--skip-build]${NC}"
echo -e "  Pull latest next, migrate, build."
echo -e "  ${DIM}With a branch name, creates it off next.${NC}"
echo -e "  ${DIM}--fresh also nukes and rebuilds the database.${NC}"
echo ""
echo -e "  ${CYAN}${BOLD}mj-catch-up${NC}  ${DIM}[--skip-build]${NC}"
echo -e "  Merge latest next into your current branch."
echo ""
echo -e "  ${CYAN}${BOLD}mj-review${NC}  ${DIM}<pr#|branch> [--skip-build]${NC}"
echo -e "  Check out a PR to test. ${CYAN}mj-review --done${NC} to go back."
echo ""
echo -e "  ${CYAN}${BOLD}mj-nuke${NC}"
echo -e "  Drop the database and rebuild from scratch."
echo ""
echo -e "  ${CYAN}${BOLD}mj-snapshot${NC}  ${DIM}save|restore|list|delete${NC}"
echo -e "  Save/restore DB snapshots. ${DIM}Turns 15 min into 30 sec.${NC}"
echo ""
echo -e "  ${DIM}──────────────────────────────────────────────${NC}"
echo ""
echo -e "  ${CYAN}${BOLD}mj-status${NC}                    ${CYAN}${BOLD}mj-help${NC}"
echo -e "  ${DIM}Health check${NC}                   ${DIM}This screen${NC}"
echo ""
